title = 'Ethereum Yellow Paper Walkthrough 1'
file_name = 'ethereum-yellow-paper-walkthrough-1'
description = 'Ethereum Yellow Paper Walkthrough 1'
tags = ['ethereum']
posted = '27/08/2023'
estimated_reading_time = 10
author = 'aoi' 
order = 5
